### PR TITLE
Add functionality to create default config file, Add test for missing build file, add pyc files to gitignore and rename test case in test_1build.py

### PR DESCRIPTION
**Pull request by Ritabrata-TW**

### CODE REVIEW

**Comment by gopinath-langote** [comment]
Hello @Ritabrata-TW 
Thanks for opening PR.

This Issue is related to Issue: https://github.com/gopinath-langote/1build/issues/84

Which means, help messages showing on this feature is going to depend upon another issue.

It will be good if we play first https://github.com/gopinath-langote/1build/issues/84

**Comment by gopinath-langote** [comment]
Though, This minimal PR is also good, 
- Adding missing test 
- `.pyc` to gitignore

**Comment by Ritabrata-TW** [comment]
Hi @gopinath-langote . 

Thanks. Working on the other issue. :)

**Comment by Ritabrata-TW** [comment]
Creating separate pull request for the issues individually.

**Pull request closed without merging**
